services:
  backend:
    build: .
    env_file: .env
    environment:
      - PORT=${PORT}
      - API_AUTHORS_PATH=${API_AUTHORS_PATH}
      - API_COURSES_PATH=${API_COURSES_PATH}
      - AUTH_LOGIN_PATH=${AUTH_LOGIN_PATH}
      - AUTH_USER_PATH=${AUTH_USER_PATH}
      - APP_URL=${APP_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB=${DB}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    ports:
      - "${PORT}:${PORT}"
